name: deploy

on:
  push:
    # branches:
    #   - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy to S3
        run: aws s3 sync ./airflow/dags/. s3://prd-airflow-data/dags

          
